<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Имя',
    'Active' => 'Активная',
    'Deactive' => 'Неактивная',
    'Save' => 'Сохранить',
    'Back' => 'Назад',
    'Delete' => 'Удалить',
    'Edit' => 'Редактировать',
    
    'Status' => 'Статус',
    'Comment' => 'Комментарий',
    
    'Catalog' => 'Каталог',
    'Total' => 'Итого',
    //Product
    'Title' => 'Название',
    'Description' => 'Описание',
    'Url' => 'Ссылка',
    'Cost' => 'Стоимость',
    'Price' => 'Цена',
    'Category' => 'Категория',
    'Products' => 'Товары',
    'Images' => 'Изображения',
    'Update' => 'Обновить',
    'Count Views' => 'Количество просмотров',
    'Create Product' => 'Добавить товар',
    'Add Product' => 'Добавить товар',
    'Update Product' => 'Обновить товар',
    'Similar products' => 'Похожие товары',
    'Cart' => 'Корзина',
    'Add to cart' => 'Добавить в корзину',
    'Quantity' => 'Количество',
    //category
    'Product Categories' => 'Категории товаров',
    'Create Product Category' => 'Создать категорию товаров',
    'Update Product Category' => 'Обновить категорию товаров',
    'Description after goods' => 'Описание после товаров',
    'User' => 'Пользователь',
    
    // order
    'Order' => 'Заказ',
    'My Orders' => 'Мои заказы',
    'Checkout' => 'Оформить заказ',
    'Select delivery method' => 'Выберите способ доставки',
    'Unknown method of delivery' => 'Неизвестный способ доставки',
    'Invalid delivery method selected' => 'Выбран недопустимый способ доставки',
    'User ID' => 'ID пользователя',
    'Delivery Method' => 'Способ доставки',
    'First Name' => 'Имя',
    'Last Name' => 'Фамилия',
    'Middle Name' => 'Отчество',
    'Phone' => 'Телефон',
    'Postcode' => 'Почтовый индекс',
    'City' => 'Город',
    'Address' => 'Адрес',
    'Created At' => 'Дата создания',
    'Updated At' => 'Дата обновления',
    'Your order has been placed successfully!' => 'Ваш заказ был успешно оформлен!',
    'Order Information' => 'Информация о заказе',
    
    // the list of order statuss
    'Order not accepted yet' => 'Заказ еще не принят',
    'Processing' => 'Принят в обработку',
    'Rejected' => 'Отклонен',
    'Canceled by user' => 'Отменен пользователем',
    'Assembling' => 'На сборке',
    'Awaiting payment' => 'Ожидает оплаты',
    'Paid' => 'Оплачен',
    'Assembled' => 'Собран',
    'Shipped to customer' => 'Отправлен клиенту',
    'Delivered to customer' => 'Получен клиентом',
    
    //stock
    'Add to Stock' => 'Добавить на склад',
    'Quantity on stock' => 'Количество на складе',
    'Stock Movements' => 'Движения запасов',
    'Product Stock Movements' => 'Движения запасов товара',
];
