<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Имя',
    'Active' => 'Активная',
    'Deactive' => 'Неактивная',
    'Save' => 'Сохранить',
    'Back' => 'Назад',
    'Delete' => 'Удалить',
    'Edit' => 'Редактировать',
    
    'Status' => 'Статус',
    'Comment' => 'Комментарий',
    // Category
    'Position' => 'Позиция',
    'Parent Category' => 'Родительская категория',
    
    'Catalog' => 'Каталог',
    'Total' => 'Итого',
    //Product
    'Title' => 'Название',
    'Description' => 'Описание',
    'Composition' => 'Состав',
    'Weight' => 'Вес',
    'Url' => 'Ссылка',
    'Cost' => 'Стоимость',
    'Price' => 'Цена',
    'Category' => 'Категория',
    'Products' => 'Товары',
    'Images' => 'Изображения',
    'Update' => 'Обновить',
    'Count Views' => 'Количество просмотров',
    'Create Product' => 'Добавить товар',
    'Add Product' => 'Добавить товар',
    'Update Product' => 'Обновить товар',
    'Similar products' => 'Похожие товары',
    'Cart' => 'Корзина',
    'Deleted' => 'Удален',
    'Active' => 'Активен',
    'Add to cart' => 'Добавить в корзину',
    'Quantity' => 'Количество',
    'This URL is already in use' => 'Этот URL уже используется',
    'Select status' => 'Выберите статус',
    'Basic information' => 'Основная информация',
    'Type' => 'Тип',
    'Rating' => 'Рейтинг',
    'Position' => 'Позиция',
    'Out of stock' => 'Нет в наличии',
    'Video' => 'Видео',
    'We don’t have enough items in stock at the moment.' => 'К сожалению, сейчас этого товара нет в достаточном количестве.',
    
    'Bulk pricing' => 'Оптовые цены',
    'Bulk quantity 1' => 'Количество для опта 1',
    'Bulk price 1' => 'Оптовая цена 1',
    'Bulk quantity 2' => 'Количество для опта 2',
    'Bulk price 2' => 'Оптовая цена 2',
    'Bulk quantity 3' => 'Количество для опта 3',
    'Bulk price 3' => 'Оптовая цена 3',
    'Set prices for different quantity ranges' => 'Установите цены для разных диапазонов количества',
    'Quantity threshold' => 'Порог количества',
    'Special price' => 'Спеццена',
    'Applies when quantity in cart meets or exceeds this value' => 'Применяется, когда количество в корзине достигает или превышает это значение',
    'Bulk discounts' => 'Оптовые скидки',
    'From' => 'От',
    'pcs.' => 'шт.',
    'Quantity in order' => 'Количество в заказе',
    'Discounted price' => 'Цена со скидкой',
    'You save' => 'Ваша выгода',
    'Discount' => 'Скидка',
    //category
    'Product Categories' => 'Категории товаров',
    'Create Product Category' => 'Создать категорию товаров',
    'Update Product Category' => 'Обновить категорию товаров',
    'Description after goods' => 'Описание после товаров',
    'User' => 'Пользователь',
    
    // order
    'Order' => 'Заказ',
    'My Orders' => 'Мои заказы',
    'Checkout' => 'Оформить заказ',
    'Select delivery method' => 'Выберите способ доставки',
    'Unknown method of delivery' => 'Неизвестный способ доставки',
    'Invalid delivery method selected' => 'Выбран недопустимый способ доставки',
    'User ID' => 'ID пользователя',
    'Delivery Method' => 'Способ доставки',
    'First Name' => 'Имя',
    'Last Name' => 'Фамилия',
    'Middle Name' => 'Отчество',
    'Phone' => 'Телефон',
    'Postcode' => 'Почтовый индекс',
    'City' => 'Город',
    'Address' => 'Адрес',
    'Created At' => 'Дата создания',
    'Updated At' => 'Дата обновления',
    'Your order has been placed successfully!' => 'Ваш заказ был успешно оформлен!',
    'Order Information' => 'Информация о заказе',
    'Your cart is empty' => 'Ваша корзина пуста',
    'View' => 'Просмотреть',
    'Order Number' => 'Номер заказа',
    'Delivery Cost' => 'Стоимость доставки',
    'Your cart is empty' => 'Ваша корзина пуста',
    'Add products from the store' => 'Добавьте товары из магазина',
    'Clear cart' => 'Очистить корзину',
    'Are you sure you want to clear your cart?' => 'Вы уверены, что хотите очистить корзину?',
    
    // the list of order statuss
    'Order not accepted yet' => 'Заказ еще не принят',
    'Processing' => 'Принят в обработку',
    'Rejected' => 'Отклонен',
    'Canceled by user' => 'Отменен пользователем',
    'Assembling' => 'На сборке',
    'Awaiting payment' => 'Ожидает оплаты',
    'Paid' => 'Оплачен',
    'Assembled' => 'Собран',
    'Shipped to customer' => 'Отправлен клиенту',
    'Delivered to customer' => 'Получен клиентом',
    
    //stock
    'Date' => 'Дата',
    'Left' => 'Осталось',
    'Add to Stock' => 'Добавить на склад',
    'Quantity on stock' => 'Количество на складе',
    'Stock Movements' => 'Движения запасов',
    'Product Stock Movements' => 'Движения запасов товара',
    'Failed to create user' => 'Неудалось создать пользователя',
    'Product Specifications' => 'Характеристики товара',
    
    // shops
    'Store Name' => 'Название магазина',
    'Create Store' => 'Создать магазин',
    'Stores' => 'Магазины',
    'Store' => 'Магазин',
    
    // Product Property translations
    'Name' => 'Название',
    'Code' => 'Код',
    'Type' => 'Тип',
    'Sort Order' => 'Порядок сортировки',
    'Required' => 'Обязательное',
    'Active' => 'Активно',
    'Created At' => 'Создано',
    'Updated At' => 'Обновлено',
    
    // Property types
    'Text Field' => 'Текстовое поле',
    'Dropdown List' => 'Выпадающий список',
    'Year' => 'Год',
    'Date' => 'Дата',
    'Checkbox' => 'Чекбокс',
    'Unknown Type' => 'Неизвестный тип',
    
    // Property Option translations
    'Property' => 'Свойство',
    'Value' => 'Значение',
    
    // Property Value translations
    'Product' => 'Товар',
    'Text Value' => 'Текстовое значение',
    'Integer Value' => 'Числовое значение',
    'Date Value' => 'Дата',
    'Boolean Value' => 'Логическое значение',
    'Option' => 'Опция',
    
    // Common
    'Yes' => 'Да',
    'No' => 'Нет',
    'Filter' => 'Фильтровать',
    
    // Controller messages
    'Options are available only for dropdown list properties' => 'Опции доступны только для свойств типа "Выпадающий список"',
    'Options saved successfully' => 'Опции успешно сохранены',
    'Option deleted' => 'Опция удалена',
    'Option not found' => 'Опция не найдена',
    
    // Новые переводы для контроллера
    'Product Properties' => 'Свойства товаров',
    'Create Property' => 'Создать свойство',
    'Create Product Property' => 'Создание свойства товара',
    'Update Product Property: {name}' => 'Редактирование свойства: {name}',
    'Update' => 'Редактировать',
    'Save' => 'Сохранить',
    'Cancel' => 'Отмена',
    'Delete' => 'Удалить',
    'Manage Options' => 'Управление опциями',
    'Toggle Status' => 'Переключить статус',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Are you sure you want to change the status?' => 'Вы уверены, что хотите изменить статус?',
    
    // Опции
    'Manage Options for: {name}' => 'Управление опциями для: {name}',
    'Add New Option' => 'Добавить новую опцию',
    'Option Value' => 'Значение опции',
    'Add Option' => 'Добавить опцию',
    'Existing Options' => 'Существующие опции',
    'Actions' => 'Действия',
    'No options found' => 'Опции не найдены',
    'Are you sure you want to delete this option?' => 'Вы уверены, что хотите удалить эту опцию?',
    'Edit Option' => 'Редактировать опцию',
    'Save Changes' => 'Сохранить изменения',
    
    // Сообщения
    'Property created successfully' => 'Свойство успешно создано',
    'Property updated successfully' => 'Свойство успешно обновлено',
    'Property deleted successfully' => 'Свойство успешно удалено',
    'Status updated successfully' => 'Статус успешно обновлен',
    'Failed to update status' => 'Не удалось обновить статус',
    'Options saved successfully' => 'Опции успешно сохранены',
    'Option deleted' => 'Опция удалена',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
    
    // ProductPropertySearch
    'Search' => 'Поиск',
    'Reset' => 'Сбросить',
    'Select Type' => 'Выберите тип',
    
    // Новые переводы для формы опций
    'Dropdown Options' => 'Варианты выпадающего списка',
    'Add Option' => 'Добавить вариант',
    'Option value' => 'Значение варианта',
    'Sort order' => 'Порядок сортировки',
    'Add options for dropdown list. Each option should have a unique value.' => 'Добавьте варианты для выпадающего списка. Каждый вариант должен иметь уникальное значение.',
    'Please add at least one option for dropdown list.' => 'Пожалуйста, добавьте хотя бы один вариант для выпадающего списка.',
    
    // Сообщения
    'Options saved successfully' => 'Варианты успешно сохранены',
    'Option values must be unique.' => 'Значения вариантов должны быть уникальными.',
    'Remove' => 'Удалить',
    'No options added yet. Click "Add Option" to create new options.' => 'Опции еще не добавлены. Нажмите "Добавить вариант" чтобы создать новые опции.',
    
    // Иконки и подсказки
    'Option value' => 'Значение варианта',
    'Sort order' => 'Порядок сортировки',
    
    'Product Properties' => 'Свойства товара',
    'Select option' => 'Выберите вариант',
    'Enter value' => 'Введите значение',
    'Required field' => 'Обязательное поле',
    
    /**
     * Colors
     */
    'Color' => 'Цвет',
    'Position' => 'Позиция',
    'Sort Order' => 'Порядок сортировки',
    'CSS Color' => 'CSS цвет',
    
    // Основные цвета
    'White' => 'Белый',
    'Gray' => 'Серый',
    'Black' => 'Черный',
    'Blue' => 'Синий',
    'Red' => 'Красный',
    'Orange' => 'Оранжевый',
    
    'Product Colors' => 'Цвета товаров',
    'Create Color' => 'Создать цвет',
    'Move up' => 'Поднять',
    'Move down' => 'Опустить',
    'Position updated successfully' => 'Позиция успешно обновлена',
    'Cannot move color up' => 'Не удалось поднять цвет',
    'Cannot move color down' => 'Не удалось опустить цвет',
    
    
    'Create Product Color' => 'Создание цвета товара',
    'Update Product Color' => 'Обновить цвет товара',
    'Back to List' => 'Назад к списку',
    'Color Preview' => 'Предпросмотр цвета',
    'Sample Text' => 'Пример текста',
    'Hex:' => 'HEX:',
    'Text Color:' => 'Цвет текста:',
    'Tip:' => 'Подсказка:',
    
    'Enter color name' => 'Введите название цвета',
    'Auto-generated from name' => 'Автоматически генерируется из названия',
    'Enter HEX color without # (e.g., FF5733)' => 'Введите HEX цвет без # (например, FF5733)',
    'Auto-assigned' => 'Автоматически назначается',
    'Active color' => 'Активный цвет',
    'Save' => 'Сохранить',
    'Cancel' => 'Отмена',
    'Available Colors' => 'Доступные цвета',

    'Select Color' => 'Выберите цвет',
    'Select a category to see available colors' => 'Выберите категорию чтобы увидеть доступные цвета',
    'All Colors' => 'Все цвета',
    'Clear filter' => 'Очистить фильтр',
    'Filter by Color' => 'Фильтр по цвету',
    
    'SEO Settings' => 'SEO Настройки',
    'Open Graph Settings' => 'Настройки Open Graph',
    'Recommended length: {length} characters' => 'Рекомендуемая длина: {length} символов',
    'Recommended length: 50-60 characters' => 'Рекомендуемая длина: 50-60 символов',
    'Recommended length: 150-160 characters' => 'Рекомендуемая длина: 150-160 символов',
    'Keywords separated by commas' => 'Ключевые слова через запятую',
    'Title for social media sharing' => 'Заголовок для публикации в социальных сетях',
    'Description for social media sharing' => 'Описание для публикации в социальных сетях',
    'URL to image for social media sharing' => 'URL изображения для публикации в социальных сетях',
    
    'Meta Title' => 'Мета-заголовок (SEO)',
    'Meta Description' => 'Мета-описание (SEO)',
    'Meta Keywords' => 'Ключевые слова (SEO)',
    'OG Title' => 'Заголовок для соцсетей (OpenGraph)',
    'OG Description' => 'Описание для соцсетей (OpenGraph)',
    'OG Image' => 'Изображение для соцсетей (OpenGraph)',
    
    // Settings translations
    'Products Per Page' => 'Товаров на странице',
    'Catalog Title' => 'Заголовок каталога',
    'Store Name' => 'Название магазина',
    'Mobile Products Per Row' => 'Товаров в строке на мобильном',
    'Multi-Store Support' => 'Поддержка мульти-магазина',
    'Default Product Image' => 'Изображение товара по умолчанию',
    'Catalog Page ID' => 'ID страницы каталога',
    'Show Wholesale Prices' => 'Отображать оптовые цены',
    
    // Common settings terms
    'Settings' => 'Настройки',
    'Key' => 'Ключ',
    'Value' => 'Значение',
    'Type' => 'Тип',
    
    // Роль для владельца магазина
    'Shop Owner' => 'Владелец магазина',
    'Shop owner role with full access rights' => 'Роль владельца магазина с полными правами доступа',
];


